list =[]
list.append(int(input("add a number:")))
list.append(int(input("add a number:")))
list.append(int(input("add a number:")))
list.append(int(input("add a number:")))
list.append(int(input("add a number:")))
list.append(int(input("add a number:")))
print(list)
input("push enter")
print(list[0])
input("push enter")
print(list[1])
input("push enter")
print(list[2])
input("push enter")
print(list[3])
input("push enter")
print(list[4])
input("push enter")
print(list[5])